### ISSUE TITLE
"Ghost" possible after death

### ISSUE THREAD

**Issue by akhahaha** [watabou/pixel-dungeon#59]
In certain conditions, a "ghost" of the player can appear after death. Includes but not limited to being killed during movement, in which case pressing the "continue movement" button will spawn the ghost.

**Comment by rodriformiga** [comment]
I have implemented this in the game, in ResumeButton class.
Changes can be seen in the commit 23b285c6e4ced73119a49254da901916e2e0088f
:+1:

**Comment by akhahaha** [comment]
Hmm, I'm still seeing this in Android 1.9.0. I'll probably take a look at it for myself when I get the chance if no one gets to it first.

**Comment by djalilhebal** [comment]
Version 1.9.2a still has this bug.

![Screenshot_20190304-211653](https://user-images.githubusercontent.com/32184973/54075010-faffac00-4299-11e9-91e3-ce6aca8de0aa.png)
![Screenshot_20190304-211700](https://user-images.githubusercontent.com/32184973/54075011-faffac00-4299-11e9-9773-33eb385b5036.png)

**Comment by ret394** [comment]
also happens in a shattered Dungeon I think.
